name: Deployment To S3

on:
  push:
    branches:
      - master # deploy only when code is on master(production) branch

jobs:
  lint-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: npm ci

    - name: lint
      run: npm run lint

    - name: build
      run: npm run build

  deploy:
    runs-on: ubuntu-18.04
    needs: lint-build
    - name: Deployment
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 sync --delete --acl public-read build/ s3://www.desertbythesearentals.com/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-1'
